In [1]:
import numpy as np

In [4]:
# One dimensional array
oneDarray = np.array([1,2,3,4,5])
print(oneDarray)

[1 2 3 4 5]


In [5]:
print(oneDarray.ndim)

1


In [11]:
# Two dimensional array
twoDarray = np.array([[1,2,3,4,5,6],[1,4,5,6]])
print(twoDarray)
print(twoDarray.ndim)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
2


In [17]:
# Three dimensional array
threeDarray = np.array([[[1,2,3], [-1,-2,-3]], [[4,5,6], [-4,-5,-6]]])
print(threeDarray)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [19]:
print(threeDarray.ndim)

3


In [24]:
# indexing numpay array
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [26]:
print(twoDarray[0])

[1 2 3]


In [27]:
print(twoDarray[0,2])

3


In [32]:
# Three D array
print(threeDarray)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [34]:
print(threeDarray[1])

[[ 4  5  6]
 [-4 -5 -6]]


In [35]:
print(threeDarray[1,1,0])

-4


In [37]:
# Iterates 2d numpy array
print(twoDarray)
for i in twoDarray:
    print(i)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [38]:
# Make every element on 1 d array iterate
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


In [42]:
# Iterates 3D numpy array
# print(threeDarray)
for i in threeDarray:
    print(i)

[[ 1  2  3]
 [-1 -2 -3]]
[[ 4  5  6]
 [-4 -5 -6]]


In [43]:
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6


In [46]:
# Create prefilled array with zero
zeroArray = np.zeros(5)
print(zeroArray)

# convert to integer value
zeroArray = zeroArray.astype(int)
print(zeroArray)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [50]:
# Create prefilled array with one
oneArray = np.ones(10)
print(oneArray)

# convert to integer value
oneArray = oneArray.astype(int)
print(oneArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [51]:
preFilledArray = np.full(5 ,2)
print(preFilledArray)

[2 2 2 2 2]


In [56]:
arrays = np.array([])
print(arrays)

for i in range(0,10):
    arrays = np.full(i,i)
    
print(arrays)

[]
[9 9 9 9 9 9 9 9 9]


In [58]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [60]:
# Adding a scalar
print(matrix + 2)

[[3 4 5]
 [6 7 8]]


In [61]:
# Substract a scalar
print(matrix - 1)

[[0 1 2]
 [3 4 5]]


In [65]:
# Multiplying a scalar
print(matrix * 10)

pyList = [[1,2,3],[4,5,6]]
print(pyList * 10)

[[10 20 30]
 [40 50 60]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [66]:
# Dividing a scalar
print(matrix / 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [67]:
# Dividing a scalar
print(matrix // 2)

[[0 1 1]
 [2 2 3]]


In [68]:
# Square a scalar
print(matrix ** 10)

[[       1     1024    59049]
 [ 1048576  9765625 60466176]]


In [69]:
# Tranpose a scalar
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [93]:
# Element wise addition numpy
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[-1,-2,-3],[-4,-5,6],[10,11,6]])
print(matrix1 + matrix2)

[[ 0  0  0]
 [ 0  0 12]
 [17 19 15]]


In [89]:
# Element wise substraction numpy

print(matrix1 - matrix2)

[[ 2  4  6]
 [ 8 10  0]]


In [90]:
# Element wise multiplication numpy

print(matrix1 * matrix2)

[[ -1  -4  -9]
 [-16 -25  36]]


In [91]:
# Element wise division numpy

print(matrix1 / matrix2)
print(matrix1 // matrix2)

[[-1. -1. -1.]
 [-1. -1.  1.]]
[[-1 -1 -1]
 [-1 -1  1]]


In [94]:
# Element matrix multiplication numpy
np.matmul(matrix1,matrix2)

array([[21, 21, 27],
       [36, 33, 54],
       [51, 45, 81]])

In [96]:
# Numpy statistic
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
np.sum(matrix1)

45

In [98]:
np.mean(matrix1)

5.0

In [99]:
np.median(matrix1)

5.0

In [101]:
np.std(matrix1)

2.581988897471611

In [102]:
np.average(matrix1)

5.0

In [103]:
np.min(matrix1)

1

In [104]:
np.max(matrix1)

9